# Generated by Django 4.2.1 on 2023-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=100000)),
                ("file", models.FileField(upload_to="media/files/academic")),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementAndNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
                ("image", models.FileField(upload_to="media/images/announcement")),
                ("file", models.FileField(upload_to="media/files/announcement")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_or_name", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="FeedbacksAndSuggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=10000)),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
                ("image", models.ImageField(upload_to="media/images/gallery")),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=20)),
                ("message", models.TextField(max_length=1000)),
                ("image", models.ImageField(upload_to="media/images/members")),
            ],
            options={
                "verbose_name_plural": "Members",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("dean", "dean"),
                            ("hod", "hod"),
                            ("dhod", "dhod"),
                            ("president", "president"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(max_length=1000)),
                ("full_name", models.CharField(default="", max_length=200)),
                ("image", models.ImageField(upload_to="media/images/message")),
            ],
        ),
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/images/newsletter")),
            ],
            options={
                "verbose_name_plural": "NewsLetter",
            },
        ),
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Fourth", "Fourth"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[("1st", "1st"), ("2nd", "2nd")], max_length=20
                    ),
                ),
                ("description", models.TextField(max_length=100000)),
                ("file", models.FileField(upload_to="media/files/syllabus")),
                ("resource_link", models.CharField(default="", max_length=100000)),
            ],
            options={
                "verbose_name_plural": "Syllabus/Resources",
            },
        ),
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
                ("file", models.FileField(upload_to="media/files/update")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
