# Generated by Django 4.2.2 on 2023-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksAndSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
