# Generated by Django 4.2.2 on 2023-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('dean', 'dean'), ('hod', 'hod'), ('dhod', 'dhod')], max_length=20)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
