# Generated by Django 4.2.1 on 2023-06-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sochapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "MemberPosition",
            },
        ),
        migrations.AlterField(
            model_name="members",
            name="position",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sochapp.memberposition"
            ),
        ),
    ]
