# Generated by Django 4.2.1 on 2023-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sochapp", "0002_memberposition_alter_members_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberposition",
            name="position",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
