# Generated by Django 4.2.2 on 2023-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, upload_to='media/files'),
        ),
    ]
