# Generated by Django 4.2.1 on 2023-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sochapp", "0003_alter_memberposition_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberposition",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
