# Generated by Django 4.2.2 on 2023-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0004_alter_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/images/members')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='media/images/message'),
        ),
    ]
