# Generated by Django 4.2.1 on 2023-06-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sochapp", "0006_alter_members_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sochapp.memberposition"
            ),
        ),
    ]
