# Generated by Django 4.2.2 on 2023-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0006_gallery_alter_members_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100000)),
                ('file', models.FileField(upload_to='media/images/gallery')),
            ],
        ),
    ]
