# Generated by Django 4.2.2 on 2023-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0007_academicresources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=20)),
                ('part', models.CharField(choices=[('First', '1st'), ('Second', '2nd')], max_length=20)),
                ('description', models.TextField(max_length=100000)),
                ('file', models.FileField(upload_to='media/images/gallery')),
            ],
        ),
    ]
