# Generated by Django 4.2.2 on 2023-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0008_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('file', models.FileField(upload_to='media/files/update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Syllabu'},
        ),
        migrations.AlterField(
            model_name='academicresources',
            name='file',
            field=models.FileField(upload_to='media/files/academic'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(upload_to='media/files/syllabus'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='part',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=20),
        ),
    ]
