# Generated by Django 4.2.2 on 2023-06-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0009_update_alter_syllabus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_or_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
