# Generated by Django 4.2.2 on 2023-06-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0011_announcementandnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/newsletter')),
            ],
            options={
                'verbose_name_plural': 'NewsLetter',
            },
        ),
        migrations.AlterModelOptions(
            name='announcementandnews',
            options={'verbose_name_plural': 'AnnouncementAndNews'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabus'},
        ),
    ]
