# Generated by Django 4.2.2 on 2023-06-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochapp', '0012_newsletter_alter_announcementandnews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='resource_link',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
